### PR TITLE
Run model with read exclusions

### LINKED ISSUE #218: Pathogens with subtypes only get model diagnostic plots for one
Because the two Influenzas and Noroviruses come from the same pathogen file and the pathogen file name is used to label the diagnostic output plots, the diagnostic plots from one subtype overwrite those from the other subtype.

### PR DESCRIPTION
**Pull request by dp-rice**
Bump the MGS data tag to remove false-positive read assignments from counts.

Updated prevalence plot:

prevalence-violin

Also, incidentally resolves #218

### CODE REVIEW

**Comment by jeffkaufman** [comment]
Would it be possible to include Brinch for HIV and HCV, since those two reads look real?

**Comment by dp-rice** [comment]
Recall that we don't have public health estimates for those. Otherwise they should be there automatically

**Comment by dp-rice** [comment]
Also @jeffkaufman I forgot to push a commit

**Comment by jeffkaufman** [comment]
Should this PR include `fits_summary.tsv`?

**Comment by jeffkaufman** [comment]
> Recall that we don't have public health estimates for those. Otherwise they should be there automatically

pinging @simonleandergrimm ;)

**Comment by dp-rice** [comment]
Ok, ready now.

**Review by jeffkaufman — APPROVED** [review]

**Pull request merged**
